### ISSUE TITLE
Problem building the example

### ISSUE THREAD

**Issue by simonePasi** [ethz-asl/ros_best_practices#5]
I have a problem in building the example...I've installed ROS Kinect instead of ROS Indigo.

Here the error code after launching "catkin build ros_package_template"

build] Found '1' packages in 0.0 seconds.                                                                            
[build] Updating package table.                                                                                       
Starting  >>> catkin_tools_prebuild                                                                                   
No handlers could be found for logger "trollius"d] [catkin_tools_prebuild:cmake - 0.7]                                
Failed    <<< catkin_tools_prebuild                [ 0.7 seconds ]                                                    
Abandoned <<< ros_package_template                 [ Unrelated job failed ]                                           
[build] Summary: 0 of 2 packages succeeded.                                                                           
[build]   Ignored:   None.                                                                                            
[build]   Warnings:  None.                                                                                            
[build]   Abandoned: 1 packages were abandoned.                                                                       
[build]   Failed:    1 packages failed.                                                                               
[build] Runtime: 0.8 seconds total.

**Comment by pfankhauser** [comment]
I can confirm that the `ros_package_template` also compiles on ROS Kinetic. I have not seen this error before, can you confirm that other packages compile correctly in your setup?

**Comment by simonePasi** [comment]
I tried compiling the "roscpp_tutorials" talker and listener packages and they works...
Can it be due to wrong installation of catkin?

**Comment by simonePasi** [comment]
I tried to reinstall catkin and rebuild catkin workspace and now it works!!!

Thanks!!!

**Comment by pfankhauser** [comment]
Ok, glad to hear!
